# Generated by Django 4.0.6 on 2023-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0002_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='edad',
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
