# Generated by Django 4.0.6 on 2023-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0006_alter_registro_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
