# Generated by Django 4.0.6 on 2023-06-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0007_alter_registro_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='edad',
        ),
    ]
