# Generated by Django 4.0.6 on 2023-06-09 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0008_remove_registro_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='edad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
