# Generated by Django 4.0.6 on 2023-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0009_registro_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='equipo',
            field=models.CharField(choices=[(0, 'Seleccione'), (1, 'Perro'), (2, 'Gato'), (3, 'Otro')], default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
