# Generated by Django 4.0.6 on 2023-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0010_alter_registro_equipo_alter_registro_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='id',
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
