# Generated by Django 4.0.6 on 2023-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0012_equipo_alter_registro_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='equipo',
            field=models.CharField(choices=[(0, 'Seleccione'), (1, 'Administrativo'), (2, 'Usuario'), (3, 'Desarrollador')], default=0, max_length=12),
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
