# Generated by Django 4.0.6 on 2023-06-16 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0013_alter_registro_equipo_delete_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idPr', models.AutoField(db_column='idProducto', primary_key=True, serialize=False, verbose_name='ID_Producto')),
                ('nombrePr', models.CharField(max_length=20)),
                ('descripcionPr', models.TextField(max_length=100)),
                ('colorPr', models.CharField(max_length=15)),
                ('materialPr', models.CharField(max_length=15)),
                ('LongitudPr', models.CharField(max_length=15)),
                ('PrecioPr', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.AlterField(
            model_name='registro',
            name='edad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
