# Generated by Django 4.0.6 on 2023-06-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0014_producto_alter_registro_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='LongitudPr',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripcionPr',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idPr',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='colorPr',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='materialPr',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombrePr',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='PrecioPr',
            new_name='precio',
        ),
    ]
