# Generated by Django 4.0.6 on 2023-06-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0016_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(max_length=20),
        ),
    ]
