# Generated by Django 4.0.6 on 2023-06-17 00:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0018_alter_registro_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscrito',
            fields=[
                ('id_suscrito', models.AutoField(db_column='idSuscrito', primary_key=True, serialize=False, verbose_name='ID_Suscrito')),
                ('monto', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('metodo_pago', models.CharField(choices=[(0, 'Seleccione'), (1, 'Visa'), (2, 'Mastercard'), (3, 'Pay pay'), (4, 'Mach'), (4, 'Tenpo'), (5, 'Otro')], default=0, max_length=12)),
                ('mensaje', models.TextField(blank=True, max_length=200, null=True)),
                ('nombre', models.ForeignKey(db_column='idNombre', on_delete=django.db.models.deletion.CASCADE, to='Documen.registro')),
            ],
        ),
    ]
