# Generated by Django 4.0.6 on 2023-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0020_remove_producto_id_producto_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
