# Generated by Django 4.0.6 on 2023-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0021_remove_producto_id_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
