# Generated by Django 4.0.6 on 2023-06-29 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0023_producto_id_producto_alter_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('metodo_pago', models.CharField(choices=[(0, 'Seleccione'), (1, 'Visa'), (2, 'Mastercard'), (3, 'Pay pay'), (4, 'Mach'), (4, 'Tenpo'), (5, 'Otro')], default=0, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('estado', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre', models.ForeignKey(db_column='idNombre', on_delete=django.db.models.deletion.CASCADE, to='Documen.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=20)),
                ('info', models.TextField(blank=True, max_length=200, null=True)),
                ('nombre', models.ForeignKey(db_column='idNombre', on_delete=django.db.models.deletion.CASCADE, to='Documen.registro')),
            ],
        ),
    ]
