# Generated by Django 4.0.6 on 2023-07-06 16:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0024_pago_historial_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='cantidad',
            new_name='cantidad_total',
        ),
        migrations.AddField(
            model_name='historial',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial',
            name='valor_total',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
