# Generated by Django 4.0.6 on 2023-07-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0025_rename_cantidad_historial_cantidad_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
