# Generated by Django 4.0.6 on 2023-07-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documen', '0026_alter_historial_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
